version: 0.2

env:
  variables:
    CONTAINER_REPOSITORY_URL: 843471151603.dkr.ecr.us-east-2.amazonaws.com/nodeapp
    TAG_NAME: latest

phases:
  install:
    runtime-versions:
     docker: 19

pre_build:
  commands:
    - $(aws ecr get-login --no-include-email)
    - docker pull $CONTAINER_REPOSITORY_URL:$TAG_NAME || true
    - echo final prebuild...

build:
  commands:
    - cd ./al2/x86_64/standard/1.0
    - docker build --cache-from $CONTAINER_REPOSITORY_URL:$TAG_NAME --tag $CONTAINER_REPOSITORY_URL:$TAG_NAME .
    - echo final build....

post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL
      - echo final postbuild


